name: Pull Request Flow

on:
  - pull_request

jobs:
  notify:
    name: Notify snapshot update
    runs-on: ubuntu-latest
    steps:
      - name: comment PR
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_BRANCH: ${{ github.base_ref }}
        with:
          msg: |
                  Thank you for sending a PR!

                  If this PR is to add a new or updated library, I would like you to run the following
                  commands to update package snapshots for automation tests.

                  First, please clone your fork of this repository somewhere and checkout your PR. At the directory...

                  - If your library supports the latest develop version of SATySFi, run

                    ```
                    scripts/update-snapshot --opam snapshot-develop.opam
                    ```

                  - If your library supports SATySFi 0.0.5, run

                    ```
                    scripts/update-snapshot --opam snapshot-stable-0-0-5.opam
                    ```

                  - If your library supports SATySFi 0.0.4, run

                    ```
                    scripts/update-snapshot --opam snapshot-stable-0-0-4.opam
                    ```

                  Finally, commit the change and push it.

                  Thanks!
